---
- name: Set experience fact
  ansible.builtin.set_fact:
    # experience: "{{ __experience.results }}"
    experience: "{{ __experience.results | default([]) | map(attribute='__experience_loop_var') | items2dict }}"

- debug:
    var: experience['url']
- name: Get Automation Experience repository files
  ansible.builtin.git:
    repo: "{{ ansible_facts['experience']['url'] }}"
    dest: "{{ __tmp_dir.path }}/{{ ansible_facts['experience']['url'].split('/')[-1] }}"
    version: "{{ ansible_facts['experience']['version'] | default('main') }}"

- name: Get all setup YAML files
  ansible.builtin.find:
    paths: '{{ __tmp_dir.path }}/{{ experience["url"].split("/")[-1] }}/{{ experiences_path }}/{{ experience["name"] }}'
    patterns: 'setup.yml,setup.yaml'
    recurse: true
  register: __experience_setup_files

- name: Set experience.path fact
  ansible.builtin.set_fact:
    experience.path: '{{ __tmp_dir.path }}/{{ experience["url"].split("/")[-1] }}/{{ experiences_path }}/{{ experience["name"] }}'

- name: Include vars
  ansible.builtin.include_vars:
    file: "{{ __experience_setup_file['path'] }}"
  loop: "{{ __experience_setup_files['files'] }}"
  loop_control:
    label: "{{ __experience_setup_file['path'] }}"
    loop_var: __experience_setup_file

- name: Execute automation controller resource configuration
  ansible.builtin.include_role:
    name: infra.controller_configuration.dispatch
  vars:
    controller_configuration_async_delay: 1
    controller_configuration_async_retries: 30
