---
- name: Check if the seed_usecases variable is set
  ansible.builtin.assert:
    that:
      - usecases is defined and usecases is not none
    fail_msg: "The usecases variable is not defined. Please set the seed_usecases variable."
