---
- name: Seeding Red Hat Ansible Portal content
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Filter valid usecases from the list
      ansible.builtin.set_fact:
        __selected_experiences: "{{ usecases | selectattr('name', 'in', seed_usecases) | list }}"

    - name: Perform pre-run checks
      ansible.builtin.include_tasks:
        file: ./pre_run_validation.yml

    - name: Create temp dir
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: __tmp_dir

    # - name: Set __experiences fact
    #   ansible.builtin.debug:
    #     var: item
    #   # ansible.builtin.set_fact:
    #   #   __experiences: "{{ __usecase }}"
    #   loop: "{{ __selected_experiences | map('dict') | list }}"
      # loop_control:
      #   label: "{{ __usecase['name'] }}"
      #   loop_var: __usecase

    - name: Load experiences
      ansible.builtin.include_tasks: load_experience.yml
      loop: "{{ __selected_experiences }}"
      loop_control:
        label: "{{ __experience_loop_var['name'] }}"
        loop_var: __experience_loop_var
      register: __experience
